#! /bin/bash

declare -a tests
declare -a langs

tests=([0]=binarytrees chameneosredux fannkuch fasta hello knucleotide mandelbrot meteor nbody nsieve nsievebits partialsums pidigits primes recursive regexdna revcomp spectralnorm sumcol threadring)

select=([0]=bigforth cal chicken cint clean cm cmucl csharp dlang erlang fbasic fpascal fsharp gambit gcc gforth ghc gnat gpp groovy gst ifc icon ikarus io java java14 javascript jruby lisaac lua mercury mlton mzscheme neko nice ocaml occam ooc oz perl petit php pike python psyco rebol regina ruby sbcl scala se smlnj stalin sq squeak stx swiprolog tcl vb vw yap yarv znn)

CVS=~dunham/shootout
GP4=~dunham/gp4/shootout

for t in ${tests[@]}
do
   for x in ${select[@]}
   do
      cp -fp $CVS/bench/$t/*$t*.$x $GP4/bench/$t 2>/dev/null
   done
done

cp -fp $CVS/website/websites/feeds/rss.xml $GP4/website/websites/feeds 2>/dev/null

cd $GP4
$GP4/bin/make_links
cd ~dunham
