#! /bin/bash

declare -a tests
declare -a langs

tests=([0]=binarytrees chameneosredux fannkuch fasta hello knucleotide mandelbrot meteor nbody nsieve nsievebits partialsums pidigits recursive regexdna revcomp spectralnorm sumcol threadring)

select=([0]=csharp)

GP4=~dunham/gp4/shootout

for t in ${tests[@]}
do
   for x in ${select[@]}
   do
      touch $GP4/bench/$t/*$t*.$x
   done
done
