#!/bin/env groovy
/*
	$Id: revcomp.groovy,v 1.1 2005-09-18 05:01:25 igouy-guest Exp $

	The Great Computer Language Shootout
	http://shootout.alioth.debian.org/

	contributed by Jochen Hinrichsen
	modified by 

        Each program should

            * read line-by-line a redirected FASTA format file from stdin
            * for each sequence:
                  o write the id, description, and the reverse-complement sequence in FASTA format to stdout

        We use the FASTA file generated by the fasta benchmark as input for this benchmark. Note: the file may include both lowercase and uppercase codes.

        Correct output for this 10KB input file (generated with the fasta program N = 1000) is in this 10KB output file.

        We use these code complements:

        code  meaning   complement
        A    A                   T
        C    C                   G
        G    G                   C
        T/U  T                   A
        M    A or C              K
        R    A or G              Y
        W    A or T              W
        S    C or G              S
        Y    C or T              R
        K    G or T              M
        V    A or C or G         B
        H    A or C or T         D
        D    A or G or T         H
        B    C or G or T         V
        N    G or A or T or C    N

        "by knowing the sequence of bases of one strand of DNA we immediately know the sequence of the DNA strand which will bind to it, this strand is called the reverse complement" 

*/

def complements = ['A':'T', 'C':'G', 'G':'C', 'T':'A', 'M':'K', 'R':'Y', 'W':'W', 'S':'S', 'Y':'R', 'K':'M', 'V':'B', 'H':'D', 'D':'H', 'B':'V', 'N':'N']

def revComp(s) {
    def rev = ""
    s.toUpperCase().each() {
        def ch = complements[it]
        if (ch == null) {
            println ""
            println (it)
        }
        rev += ch
    }
    rev
}

System.in.newReader().eachLine() { line ->
    println (line.startsWith(">") ? line : revComp(line))
}

// EOF
