# The Computer Language Benchmarks Game
# $Id: Makefile.site_u64q,v 1.6 2008-07-30 01:50:03 igouy-guest Exp $


# MUST set SITE_NAME and local SITE_ROOT
SITE_NAME := u64q
SITE_ROOT := ~/Documents/benchmarksgame

# source in CVS
SOURCE_ROOT := ~/shootout/bench

# makefiles in CVS
MAKE_ROOT := ~/shootout/nanobench/makefiles

# scripts in CVS
NANO_BIN := ~/shootout/nanobench/bin

# data files in CVS
DATA_ROOT := $(SOURCE_ROOT)/../website/desc



# MUST set which source directories to search
SRC_DIRS := \
 nsieve \


# binarytrees \
# chameneosredux \
# fannkuch \
# fasta \
# knucleotide \
# mandelbrot \
# meteor \
# nbody \
# nsieve \
# nsievebits \
# partialsums \
# pidigits \
# recursive \
# regexdna \
# revcomp \
# spectralnorm \
# threadring 



# ALLOW these helper file extensions to be available unchanged 
# from the working directory - they will never be measured
ALLOW := \
 sq cm



# ONLY measure files with these extensions 
# if there are none, measure files with any extension not ALLOWed or IGNOREd
ONLY := \



# IGNORE files with these extensions, if there are no ONLY extensions
IGNORE := \
 parrot slang octave cyc tcc gwydion regina \
 neko xds stx proto icon \
 squeak vw rhino sbcl




SITE_MAKEFILES := $(MAKE_ROOT)/$(SITE_NAME)

.EXPORT_ALL_VARIABLES:

.PHONY: benchmarks mkcsv cplogs highlight $(selected_source_directories) 



all: benchmarks




# don't seem able to get both these to work? 
# just one or the highlightother which ever happens first
#benchmarks: SUBMK := benchmarks
#benchmarks: SUBROOT := $(SOURCE_ROOT)
#benchmarks: $(selected_source_directories)

#cplogs: SUBMK := cplogs
#cplogs: SUBROOT := $(SITE_ROOT)
#cplogs: $(selected_source_directories)

#hilite: SUBMK := hilite
#hilite: SUBROOT := $(SITE_ROOT)
#hilite: $(selected_source_directories)

$(SRC_DIRS):
	-@$(MAKE) -C $(SUBROOT)/$@/log \
		-f $(SITE_MAKEFILES)/Makefile_$(SITE_NAME)_$@ $(SUBMK)



benchmarks: 
	-@for d in $(SRC_DIRS) ; do \
		( $(MAKE) -C $(SOURCE_ROOT)/$$d \
                          -f $(SITE_MAKEFILES)/Makefile_$(SITE_NAME)_$$d ) ; \
		done


mkcsv:
	@$(NANO_BIN)/mkcsv

cplogs: 
	-@for d in $(SRC_DIRS) ; do \
		( $(MAKE) -C $(SITE_ROOT)/$$d/log \
                          -f $(SITE_MAKEFILES)/Makefile.cptest) ; \
		done


highlight: 
	-@for d in $(SRC_DIRS) ; do \
		( $(MAKE) -C $(SITE_ROOT)/$$d/sym \
			-f $(SITE_MAKEFILES)/Makefile.highlight) ; \
		done




