#!/bin/sh

# copy and rename generic smalltalk files into ./files subdirectory

ext=.squeak
ST_HOME=/opt/Squeak-3.9-8
ST_IM=Squeak3.9-final-7067.image

if [ ! -d ./files ]; then
   mkdir ./files
fi
cp ../st/*.st ./files

for each in $(ls ./files/*.st)
do
   prefix=${each%.st}
   id=${prefix##*-}

   if [ $prefix != $id ]; then
      preprefix=${prefix%.st*}
      mv $each $preprefix$ext-$id$ext
   else
      mv $each $prefix$ext
   fi

done

cp ./*$ext ./files

cp ./files/* $ST_HOME
cp mksq.sq $ST_HOME

cd $ST_HOME
squeak -headless $ST_HOME/$ST_IM $ST_HOME/mksq.sq
