#!/bin/sh

# copy and rename generic smalltalk files into ./files subdirectory

ext=.squeak
ST_HOME=/opt/shootout/Squeak
ST_IM=squeak.image

if [ ! -d ./files ]; then
   echo "Creating 'files' directory."
   mkdir ./files
fi
cp ../st/*.st ./files
cp ./*.st ./files

echo "Changing file settings"
for each in $(ls ./files/*.st)
do
   prefix=${each%.st}
   id=${prefix##*-}

   if [ $prefix != $id ]; then
      preprefix=${prefix%.st*}
      echo "$each -> $preprefix$ext-$id$ext"
      mv $each $preprefix$ext-$id$ext
   else
      echo "$each -> $preprefix$ext"
      mv $each $prefix$ext
   fi
done
echo "Copying files..."
cp ./*$ext ./files

cp ./files/* $ST_HOME
cp mksq.sq $ST_HOME

cd $ST_HOME
echo "Currently in `pwd`"
echo "Running: squeak -headless $ST_HOME/$ST_IM $ST_HOME/mksq.sq"
squeak -headless $ST_HOME/$ST_IM $ST_HOME/mksq.sq

echo "Completed."
