# $Id: 
include ../../Make.header

TEST    := primes
TITLE   := Prime Function


OO2COPTS := -A --no-rtc

RUNTESTS := $(MINIBENCH) --conf ../../Minibench.conf \
	  --range 100,1000,10000

include ../../Make.footer
