<p>Each program should</p>
<ul>
  <li>read line-by-line a redirected <a href="http://en.wikipedia.org/wiki/Fasta_format">FASTA format</a> file from stdin</li>
  <li>extract DNA sequence THREE</li>

  <li><strong>define a procedure/function</strong> to update a hashtable of k-nucleotide keys and count values, for a particular reading-frame &#8212; even though we'll combine k-nucleotide counts for all reading-frames (grow the <strong>hashtable</strong> from a small default size)</li>

  <li>write the code and percentage frequency, for <strong>all</strong> the 1-nucleotide and 2-nucleotide sequences, sorted by descending frequency and then ascending k-nucleotide key</li>
  <li>count <strong>all</strong> the 3- 4- 6- 12- and 18-nucleotide sequences, and write the count and code for specific sequences</li>
</ul>


<p>We use FASTA files generated by the <a href="benchmark.php?test=fasta&amp;lang=all&amp;sort=<?=$Sort;?>">fasta benchmark</a> as input for this benchmark. Note: the file may include both lowercase and uppercase codes.</p>

<p>Correct output for this 100KB <a href="iofile.php?test=<?=$SelectedTest;?>&amp;lang=<?=$SelectedLang;?>&amp;sort=<?=$Sort;?>&amp;file=input">input file</a> (generated with the fasta program N = 10000), is</p>
<pre>
A 30.284
T 29.796
C 20.312
G 19.608

AA 9.212
AT 8.950
TT 8.948
TA 8.936
CA 6.166
CT 6.100
AC 6.086
TC 6.042
AG 6.036
GA 5.968
TG 5.868
GT 5.798
CC 4.140
GC 4.044
CG 3.906
GG 3.798

562     GGT
152     GGTA
15      GGTATT
0       GGTATTTTAATT
0       GGTATTTTAATTTATAGT
</pre>
<br />

<p>In practice, less brute-force would be used to calculate k-nucleotide frequencies, for example <a href="http://www.biorecipes.com/VirusClassification/code.html">Virus Classification using k-nucleotide Frequencies</a> and <a href="http://www.hicomb.org/HiCOMB2002/papers/HICOMB2003-03.pdf">A Fast Algorithm for the Exhaustive Analysis of 12-Nucleotide-Long DNA Sequences. Applications to Human Genomics</a> (105KB pdf).</p>

