# $Id: Makefile,v 1.1 2006-11-08 01:00:06 igouy-guest Exp $
include ../../Make.header

TEST    := meteor
TITLE   := Meteor Puzzle Solver



RUNTESTS := $(MINIBENCH) --conf ../../Minibench.conf \
	  --range 0

include ../../Make.footer
