#!/bin/bash
# The Computer Language Benchmarks Game
# $Id: nano,v 1.1 2008-07-25 06:02:12 igouy-guest Exp $

# copy to a local directory and edit $SITE_NAME

~/shootout/nanobench/makefiles/$SITE_NAME/nano

