<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">
<html>
<head>
  <title>The Great Computer Language Shootout</title>
  <meta name="keywords" content="performance, benchmark, computer, algorithms, languages, compare, cpu, memory"> 
</head>
<body bgcolor="#ffffff">

<table width="100%">
<tr>
<td>
<h2><!--#echo var="TITLE" --></h2>
</td>
<td align="right">
<a href="index.phtml">Back to the Language Shootout</a><br>
</td>
</tr>
</table>

<hr size="5" noshade>
