<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">
<html>
<head>
  <title>The Great Computer Language Shootout</title>
  <meta name="keywords" content="performance, benchmark, computer, algorithms, languages, compare, cpu, memory"> 
  <link REL="stylesheet" TYPE="text/css" HREF="../css/tigris.css" />
  <link REL="stylesheet" TYPE="text/css" HREF="../css/inst.css" />
</head>

<div id="banner">
<table width="100%">
<tr><td><h2>The Great Computer Language Shootout</h2></td>
<td align="right">
  <a href="index.php">Back to the Language Shootout</a><br>
</td>
</tr>
</table>

<hr size="5" noshade>
