<p>
<center>
<a href="http://www.bagley.org/~doug/shootout/">[The Original Shootout]</a> &nbsp; 
<a href="../../news.phtml">[NEWS]</a> &nbsp; 
<a href="../../faq.shtml">[FAQ]</a> &nbsp; 
<a href="../../method.shtml">[Methodology]</a> &nbsp; 
<a href="../../ack.shtml">[Acknowledgements]</a> &nbsp; 
<a href="../../craps.phtml">[Scorecard]</a> &nbsp; 
<a href="../../conclusion.shtml">[Conclusion]</a> &nbsp; 
</center>
<br>
