# The Computer Language Benchmarks Game
# $Id: Makefile.site_gp4,v 1.2 2008-07-25 00:27:29 igouy-guest Exp $


# MUST set SITE_NAME and local SITE_ROOT
SITE_NAME := gp4
SITE_ROOT := ~/benchmarksgame

# source in CVS
SOURCE_ROOT := ~/gp4/shootout/bench

# makefiles in CVS
MAKE_ROOT := ~/shootout/nanobench/makefiles

# scripts in CVS
NANO_BIN := ~/shootout/nanobench/bin



# MUST set which source directories to search
selected_source_directories := \
 fannkuch

# binarytrees \
# chameneosredux \
# fannkuch \
# fasta \
# knucleotide \
# mandelbrot \
# meteor \
# nbody \
# nsieve \
# nsievebits \
# partialsums \
# pidigits \
# recursive \
# regexdna \
# revcomp \
# spectralnorm \
# sumcol \
# threadring \



# implicitly attempt to measure all files in the source directories [][*]
# or explicitly select these file extensions to measure 
SELECT := \
 clean gcc scala



# implicitly attempt to measure all files in the source directories []
# or explicitly ignore these file extensions 
IGNORE := \
 cm proto sq stx



SITE_MAKEFILES := $(MAKE_ROOT)/$(SITE_NAME)

.EXPORT_ALL_VARIABLES:

all:
	-@for d in $(selected_source_directories) ; do \
		( $(MAKE) -C $(SOURCE_ROOT)/$$d \
                          -f $(SITE_MAKEFILES)/Makefile_$(SITE_NAME)_$$d ) ; \
		done









