#!/bin/sh
$VISUALWORKS/bin/linux86/vwlinux86 $VISUALWORKS/preview/packaging/base.im -doit "'FastDictionaryAccumulation.st' asFilename fileIn. 'stdio-fixes-base.st' asFilename fileIn. Parcel ensureLoadedParcel: 'Regex11' withVersion: ''. 'regex-fixes.st' asFilename fileIn. Parcel loadParcelFrom: 'parcels/Shootout.pcl'. HeadlessImage current saveHeadless: 'benchmarks'. ObjectMemory quit"
