#!/bin/sh

# copy and rename generic smalltalk files into ./files subdirectory

# add method send as last line

ext=.gst
ST_HOME=/usr/local/bin/gst
ST_IM=/usr/local/share/smalltalk/gst.im

if [ ! -d ./files ]; then
   mkdir ./files
fi
cp ../st/*.st ./files
cp ./*.st ./files

for each in $(ls ./files/*.st)
do
   prefix=${each%.st}
   id=${prefix##*-}
   path=${each%%.st}


   if [ $prefix != $id ]; then
      preprefix=${prefix%.st*}
      name=${preprefix##*/}

      cat >> $each <<- EOF

	Tests $name$id!
EOF

      mv $each $preprefix$ext-$id$ext

   else
      name=${path##*/}

      cat >> $each <<- EOF

	Tests $name!
EOF

      mv $each $prefix$ext
   fi
done

cp ./*$ext ./files


