# The Computer Language Benchmarks Game
# $Id: Makefile.site_debian,v 1.2 2008-07-28 17:40:40 igouy-guest Exp $


# MUST set SITE_NAME and local SITE_ROOT
SITE_NAME := debian
SITE_ROOT := ~/benchmarksgame

# source in CVS
SOURCE_ROOT := ~/shootout/bench

# makefiles in CVS
MAKE_ROOT := ~/shootout/nanobench/makefiles

# scripts in CVS
NANO_BIN := ~/shootout/nanobench/bin

# data files in CVS
DATA_ROOT := $(SOURCE_ROOT)/../website/desc



# MUST set which source directories to search
selected_source_directories := \
 nsieve \


# binarytrees \
# chameneosredux \
# fannkuch \
# fasta \
# knucleotide \
# mandelbrot \
# meteor \
# nbody \
# nsieve \
# nsievebits \
# partialsums \
# pidigits \
# recursive \
# regexdna \
# revcomp \
# spectralnorm \
# threadring 



# ALLOW these helper file extensions to be available unchanged 
# from the working directory - they will never be measured
ALLOW := \
 sq cm



# ONLY measure files with these extensions 
# if there are none, measure files with any extension not ALLOWed or IGNOREd
ONLY := \



# IGNORE files with these extensions, if there are no ONLY extensions
IGNORE := \
 parrot slang octave cyc tcc gwydion regina \
 neko xds stx proto icon \
 squeak vw rhino sbcl




SITE_MAKEFILES := $(MAKE_ROOT)/$(SITE_NAME)

.EXPORT_ALL_VARIABLES:

all:
	-@for d in $(selected_source_directories) ; do \
		( $(MAKE) -C $(SOURCE_ROOT)/$$d \
                          -f $(SITE_MAKEFILES)/Makefile_$(SITE_NAME)_$$d ) ; \
		done









